[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  environment = { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "" }

[context.deploy-preview]
  environment = { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "" }

[context.branch-deploy]
  environment = { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
