[build]
  command = "npm ci && npm run netlify-build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22.15.1"
  NPM_FLAGS = "--no-optional"
