[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "" }

[build.environment]
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
